### ISSUE TITLE
collapse class makes impossible to configure email notifications

### ISSUE THREAD

**Issue by FrancoAA** [aldryn/aldryn-forms#93]
This is how the edit modal looks when I am creating a Form with email notifications with the collapse, as you can see the configuration inputs are missing.

![with_collapse](https://cloud.githubusercontent.com/assets/2428911/15656505/75c63692-267e-11e6-9f5e-7b378cf27fd6.png)

This is how it looks with the collapse class commented out on aldryn_forms/contrib/email_notifications/cms_plugins.py

![without_collapse](https://cloud.githubusercontent.com/assets/2428911/15656504/75c53634-267e-11e6-9f07-ad2a6ff7cda6.png)

the version that I'm using is 2.1.1

**Comment by czpython** [comment]
@FrancoAA 
Hello,
This is sadly intentional behavior.
When creating email notifications it's required that the notification is saved first (by choosing a theme) and then you can modify the rest of the fields.

The reason for this is that email notification forms can be configured per form and so it's necessary for the notification to be saved in order to have access to the form and fetch the form configuration.

**Comment by FrancoAA** [comment]
I have to say that is confusing, but anyway

Thanks ;)

2016-05-30 18:07 GMT-03:00 Paulo <notifications@github.com>:

> Closed #93 <https://github.com/aldryn/aldryn-forms/issues/93>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aldryn/aldryn-forms/issues/93#event-676344110>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACUP7-XZRBXHiV-B7PWSJcjDqM0-7J3cks5qG1GugaJpZM4Ip-z4>
> .
>



-- 
*Franco Andrés Alarcón*
